on:
  - push
  - pull_request

jobs:
  samples-build-VS-2019:
  runs-on: windows-2019

  strategy:
    matrix:
      configuration: [Release]
      platform: [x86]

  steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

  -   name: Build solution
      run: msbuild 'desmume/src/frontend/windows/DeSmuME.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}
