name: build desmume windows solution

on:
  - push
  - pull_request

jobs:
  build-sln:
    runs-on: windows-2019

    strategy:
      matrix:
        configuration: [Release]
        platform: [x86]

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Build solution
        run: msbuild 'desmume/src/frontend/windows/DeSmuME.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}
